Repository dfe-analytical-services/local-authority-interactive-tool, pull requests merged in 2024-12, with the labels that each got.

#53 Repo tidy up
  02_dev/create_your_own_page/create_own_table_dev_app.R
  R/fn_helper_functions.R
  R/fn_load_data.R
  R/fn_ui_layout.R
  R/lait_modules/mod_app_helpers.R
  R/lait_modules/mod_create_own_charts.R
  R/lait_modules/mod_create_own_table.R
  R/lait_modules/mod_info_page.R
  R/lait_modules/mod_la_lvl_charts.R
  R/lait_modules/mod_metadata.R
  R/lait_modules/mod_region_charts.R
  R/lait_modules/mod_stat_n_charts.R
  R/ui_panels/create_your_own_panel.R
  R/ui_panels/info_page.R
  R/ui_panels/la_level_panel.R
  R/ui_panels/region_level_panel.R
  R/ui_panels/stat_n_level_panel.R
  R/ui_panels/support_panel.R
  R/ui_panels/user_guide.R
  server.R
  tests/testthat/test-UI-01-basic_load.R
  www/custom_js.js
  www/dfe_shiny_gov_style.css
Labels: enhancement

#52 Added GA4 key
  global.R
  google-analytics.html
Labels: eesp/maintenance

#54 Completing accessibility statement
  R/ui_panels/accessibility_panel.R
Labels: eesp/accessibility
